---
title: Aldosimon.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: aldosimon.com
metadescription: aldosimon.com adalah website pribadi Ewaldo Simon Hiras berfokus
  di bidang digital forensik, komputer forensik, incident response, dan tentu saja
  berbagai hal-hal random. est. 2009
metakeyword: digital forensik, komputer forensik, incident response, forensic, forensik
metaauthor: Ewaldo Simon Hiras
description: DFIR & random stuff
avatar: https://raw.githubusercontent.com/aldosimon/aldosimon.github.io/master/images/logo.png
footer-links:
  dribbble: 
  email: aldo@aldosimon.com
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: aldosimon
  pinterest: 
  rss: 
  twitter: aldosimon
  stackoverflow: 
  youtube: 
  googleplus: 
  letterboxd: aldosimon
google_analytics: UA-158592968-1
url: aldosimon.com
baseurl: 
excerpt_separator: "<!--more-->"
paginate: 5
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
